### ISSUE TITLE
' Undefined index: path' Fatal Error

### ISSUE THREAD

**Issue by andrejhronco** [cables-gl/cables-wordpress-plugin#5]
Hi, having an issue with the plugin when I try and access it in the admin:

```
Notice: Undefined index: path in /var/www/wp-content/plugins/cables-wpplugin/src/Api/Cables.php on line 67

Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /var/www/wp-content/plugins/cables-wpplugin/src/Api/Cables.php:108 
Stack trace: 
#0 /var/www/wp-content/plugins/cables-wpplugin/src/Backend.php(119): Cables\Plugin\Api\Cables->getAccountInfo() 
#1 /var/www/wp-includes/class-wp-hook.php(303): Cables\Plugin\Backend->cables_dashboard() 
#2 /var/www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() 
#3 /var/www/wp-includes/plugin.php(470): WP_Hook->do_action() 
#4 /var/www/wp-admin/admin.php(259): do_action() 
#5 {main} thrown in /var/www/wp-content/plugins/cables-wpplugin/src/Api/Cables.php on line 108
```

**Comment by andrejhronco** [comment]
seemed to be an issue on my side of things.
